version: '1.9'

services:
  php:
    build: 
      context: ./php/
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    links:
      - db
    ports:
      - 8081:80
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
volumes:
  mysql-data: